name: Build Image

on:
  push:
    branches: 
      - main

defaults:
  run:
    # GitHub Actions run without a TTY device. This is a workaround to get one,
    # based on https://github.com/actions/runner/issues/241#issuecomment-2019042651
    shell: 'script --return --quiet --log-out /dev/null --command "sh -e {0}"'

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    container:
      image: progrium/env86:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create image
        run: |
          make vm
          tar -czf apptron-vm.tgz -C dist .

      - uses: ncipollo/release-action@v1
        with:
          tag: "release"
          allowUpdates: true
          artifacts: "apptron-vm.tgz"